# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        node-version: 20.7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build front-end app
      run: |
        cd ./KenticoInspector.WebApplication/ClientApp
        npm i
        npm run build
    - name: Build dotnet app
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish client application
      run: |
        cd .\KenticoInspector.WebApplication
        dotnet publish KenticoInspector.WebApplication.csproj /p:PublishDir=..\publish -c Release -r win-x64 --self-contained true
        mkdir "..\publish\ClientApp\dist"
        cd .\ClientApp
        Copy-Item ".\dist\*" -Recurse -Destination "..\publish\ClientApp\dist\"
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: KInspector
        path: .\publish
